// Fetch the WOFF2 files for the bundled font set from Google Fonts and write a
// self-contained fonts/fonts.css with RELATIVE url() (just filenames). compose.mjs
// rewrites those to absolute file:// URLs at render time.
//
// Why bundle locally: deterministic rendering (no network, no FOUT) and so the
// tool is fully portable when handed to someone else.
//
// All four families are SIL OFL and support Cyrillic + Latin — required because
// Pavel's carousels are primarily in Russian. (The ave-ai landing uses Cinzel,
// which has NO Cyrillic; the seed `ave-roman` reference swaps it for Playfair
// Display + Lora, which do.)
//
// Run: npm run fonts   (re-run only to refresh/extend the font set)

import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FONTS_DIR = join(__dirname, '..', 'fonts');

// A modern desktop UA makes Google Fonts serve woff2 (its best format).
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

// Keep weights minimal but enough for all token roles.
const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Playfair+Display:wght@500;600;700;800' +
  '&family=Lora:ital,wght@0,400;0,500;0,600;1,400;1,500' +
  '&family=Inter:wght@400;500;600;700' +
  '&family=IBM+Plex+Mono:wght@400;500;600' +
  '&display=swap';

// Only bundle the subsets we need (Russian + English). Drops greek/vietnamese etc.
const KEEP_SUBSETS = new Set(['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext']);

function slug(s) {
  return String(s).toLowerCase().replace(/['"]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

async function cleanFontsDir() {
  await mkdir(FONTS_DIR, { recursive: true });
  for (const f of await readdir(FONTS_DIR)) {
    if (f.endsWith('.woff2') || f === 'fonts.css') await rm(join(FONTS_DIR, f), { force: true });
  }
}

async function main() {
  await cleanFontsDir();

  console.log('fetching font CSS…');
  const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts CSS request failed: ${res.status}`);
  const css = await res.text();

  // Pass 1: collect every @font-face (with its preceding /* subset */ comment)
  // WITHOUT mutating css — mutating mid-iteration corrupts the regex cursor.
  const faceRe = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  const rewrites = []; // { url, file }
  const keepUrls = new Set();
  let m;
  while ((m = faceRe.exec(css))) {
    const subset = m[1];
    const body = m[2];
    const url = (body.match(/url\((https?:\/\/[^)]+?)\)/) || [])[1];
    if (!url) continue;
    if (!KEEP_SUBSETS.has(subset)) continue;
    const fam = (body.match(/font-family:\s*['"]?([^;'"]+)['"]?/) || [])[1]?.trim() || 'font';
    const weight = (body.match(/font-weight:\s*([^;]+)/) || [])[1]?.trim() || '400';
    const style = (body.match(/font-style:\s*([^;]+)/) || [])[1]?.trim() || 'normal';
    const file = `${slug(fam)}-${weight}-${style}-${subset}.woff2`;
    rewrites.push({ url, file });
    keepUrls.add(url);
  }

  // Pass 2: rewrite css. Drop @font-face blocks whose subset we skipped, and
  // swap kept remote URLs for local filenames.
  let outCss = css.replace(faceRe, (block, subset, body) => {
    const url = (body.match(/url\((https?:\/\/[^)]+?)\)/) || [])[1];
    if (!url || !keepUrls.has(url)) return ''; // drop dropped subsets
    return block;
  });
  for (const { url, file } of rewrites) outCss = outCss.split(`url(${url})`).join(`url(${file})`);

  // Pass 3: download (dedupe by file).
  const byFile = new Map();
  for (const r of rewrites) byFile.set(r.file, r.url);
  console.log(`downloading ${byFile.size} woff2 files…`);
  let done = 0;
  for (const [file, url] of byFile) {
    const r = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!r.ok) throw new Error(`download failed (${r.status}): ${url}`);
    await writeFile(join(FONTS_DIR, file), Buffer.from(await r.arrayBuffer()));
    if (++done % 8 === 0) console.log(`  ${done}/${byFile.size}`);
  }

  const header =
    '/* Auto-generated by scripts/fetch-fonts.mjs — do not edit by hand.\n' +
    '   url() are relative filenames; compose.mjs rewrites them to file:// at render time.\n' +
    '   Fonts: Playfair Display, Lora, Inter, IBM Plex Mono — SIL OFL, Cyrillic + Latin. */\n\n';
  await writeFile(join(FONTS_DIR, 'fonts.css'), header + outCss.replace(/\n{3,}/g, '\n\n').trim() + '\n', 'utf8');
  console.log(`done: ${byFile.size} files + fonts.css in ${FONTS_DIR}`);
}

main().catch((e) => {
  console.error('fetch-fonts failed:', e.message);
  process.exit(1);
});
